name: $(SemVer)

# Build Matrix
# OS/TFM:                       Windows_NT, Linux, Darwin
# netstandard1.6 + net46            x
# netstandard1.6                             (x)     (x)


# Test Matrix
# OS/Runtime:   Windows_NT, Linux, Darwin
# net46             x
# netcoreapp3.1     x         x      x

variables:
  BuildRev: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  SemVer: $[format('{0:yyyy}.{0:MM}.{0:dd}-pre{1}', pipeline.startTime, variables.BuildRev)]
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true

schedules:
- cron: "22 */1 * * *"
  displayName: Scheduled Build
  always: true
  branches:
    include:
    - master

trigger:
  batch: true
  branches:
    include:
    - master

pr:
  autoCancel: true
  branches:
    include:
    - master

stages:
- template: az-templates/stage-build.yml
